# Generated by Django 2.2 on 2020-10-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
