# Generated by Django 2.2 on 2020-11-06 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20201027_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecategory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cms.Article'),
        ),
        migrations.AlterField(
            model_name='author',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cms.Article'),
        ),
        migrations.AddConstraint(
            model_name='readinghistory',
            constraint=models.UniqueConstraint(fields=('article', 'user'), name='unique_readinghistory'),
        ),
    ]
