# Generated by Django 2.2 on 2020-11-06 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20201106_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='article',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='cms.Article'),
        ),
    ]
