# Generated by Django 2.2 on 2020-11-06 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20201106_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='category',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='cms.Category'),
        ),
        migrations.AlterField(
            model_name='articletags',
            name='tag',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='cms.Tag'),
        ),
        migrations.AlterField(
            model_name='readinghistory',
            name='article',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='cms.Article'),
        ),
    ]
